### ISSUE TITLE
Problems with Compiling,

### ISSUE THREAD

**Issue by Phili86** [prysme01/DotMatrixDisplay#2]
Hi, i have some Problems with Compiling, i ddnt use the OLED, is it possible to use without? if i Compile the Sketch ther are som Problems and it dosent work. If there is sombodey who can help i will upload some Codes...
Greetz

**Comment by prysme01** [comment]
Hi, it should work without an OLED display.
What is the error message ?
Have you tried to remove this line #define USE_OLED_DISPLAY  in the .ino file ?
