### ISSUE TITLE
Time/Date/Temp in message

### ISSUE THREAD

**Issue by acestu** [prysme01/DotMatrixDisplay#3]
Hi,
All working but

Could you tell me how to add the time or date or temperature into the jason message please, and is it possible to stack messages up so that they display one after another ?

Thanks In advance
Stuart

**Comment by acestu** [comment]
Hi,

I can see from the code that you can add the time or temperature somehow, and it says that it can read a TODO file, no instructions how to though, any help appreciated...

Thanks
Stuart

**Comment by prysme01** [comment]
Hi, 

Date and time is not working anymore, it was a test at the beginning, if you want to display anything including date and time, you have to wrote to the MQTT topic the time and send it again 1 seconde later.

the text file reading is not implemented, and won't be as I say the whole program is expecting to display whatever you send to the MQTT topic.

**Comment by acestu** [comment]
Hi Prysme01,

Thanks for replying, I will see if I can make it work

Stuart
