### ISSUE TITLE
wrong schematic?

### ISSUE THREAD

**Issue by fragolinux** [prysme01/DotMatrixDisplay#4]
schematic seems wrong... there's no connection from ds18b20 to positive 3.3V, and there's a jumper right below it that connects vcc and gnd together... and data pin is connected to d1 in schematic, and to d4 in code...

**Comment by fragolinux** [comment]
even display links are wrong between schematic and code, and the ds18b20 in code is linked to d4, in image to d1

**Comment by prysme01** [comment]
yes sorry, I will remove the schematic, it has changed since and the code is not synced.

**Comment by fragolinux** [comment]
so you'll republish an updated one, or at least publish a textual version in opening readme.md? thanks
