### ISSUE TITLE
Support of P3 64x32 RGB LED Matrix?

### ISSUE THREAD

**Issue by hallard** [prysme01/DotMatrixDisplay#5]
Awesome project,
It's not an issue, but I'm using JEEDOM also and got this nice [64x32 RGB LED Matrix](https://fr.aliexpress.com/item/P3-RGB-pixel-panel-HD-display-64x32-dot-matrix-p3-smd-rgb-led-module/32728985432.html) with custom adapter open sourced
https://github.com/hallard/WeMos-Matrix-Shield

Would be awesome to support this display, the library exists so may be it could be easy.
You can check out the original[project](https://www.instructables.com/id/Morphing-Digital-Clock/)

**Comment by prysme01** [comment]
Hello charles, 

I would be able to do it, but I need to have this matrix here to test it.
One day, maybe.

**Comment by hallard** [comment]
Thanks,
Makes sense, I'm waiting for the V1.2 of my PCB adapters for this Matrix, I can send you one with a Wemos assembled if it can help to contrib ;-)

**Comment by prysme01** [comment]
Sure I could work on it if you send it to me.

**Comment by hallard** [comment]
Ok, get back back here when I receive the adapter boards
