### ISSUE TITLE
great work but ...

### ISSUE THREAD

**Issue by bandric1** [prysme01/DotMatrixDisplay#6]
Can you update the project it cannot be compiled with arduino when i try to compile get this error BearSSLHelpers.cpp:30:24: fatal error: StackThunk.h:

i have solved other library issues but cannot solve this one no matter what i do.

**Comment by prysme01** [comment]
Hello, I don't have an arduino so this project has been done to be used on a weemos esp8266. I don't use anything in particular, but I won't be able to fix it. sorry.

**Comment by bandric1** [comment]
i used arduino ide for compling i also use wemos but get that error

**Comment by prysme01** [comment]
Let me check out my code and try it

**Comment by bandric1** [comment]
I dont get u on this one, what do you mean?

**Comment by prysme01** [comment]
I've just download a fresh Arduino IDE and my code from github it works fine.

Build options changed, rebuilding all
Sketch uses 337428 bytes (32%) of program storage space. Maximum is 1044464 bytes.
Global variables use 32304 bytes (39%) of dynamic memory, leaving 49616 bytes for local variables. Maximum is 81920 bytes.

All I've done is : 
Adding a new board in Arduino IDE ( copy the following and paste into your Preferences dialog and select OK: http://arduino.esp8266.com/stable/package_esp8266com_index.json  )
Select Board Weemos D1

Copy the library folder from my code into C:\Users\esale\Documents\Arduino\libraries
Compile complain about WifiManager error, I've update the WifiManager from tzapu to 0.14.0 and it compile fine.

I don't understand where you get this error from BearSSLHelpers.

**Comment by bandric1** [comment]
Ok i guess ive done some stupit things with arduino and it knocked me out.
Thanks.

**Comment by bandric1** [comment]
There is one more question i use credentials to login to my mqtt. I didnt find anywhere in .ino exept the ip and topic.

**Comment by prysme01** [comment]
you are right, I did not manage credentials, the topic has to be public, so no user/password.
