### ISSUE TITLE
MQTT (ioBroker) problems

### ISSUE THREAD

**Issue by capitaenz** [prysme01/DotMatrixDisplay#7]
Hello,
Unfortunately, I have problems creating the data points in the IOBroker (MQTT adapter).

![jeedom](https://user-images.githubusercontent.com/1240236/61995163-c9d71b00-b084-11e9-84fd-c1afb9468e44.JPG)

The display is running, it is being ticked "WIFI Ready" is displayed in the log of the IOBroker:

`mqtt.0	2019-07-27 15:27:53.693	info	Client [ESP32Client] publishOnSubscribe
mqtt.0	2019-07-27 15:27:53.693	info	Client [ESP32Client] subscribes on "mqtt.0.jeedom.message"
mqtt.0	2019-07-27 15:27:53.685	info	Client [ESP32Client] reconnected. Old secret 1564234039837_8955. New secret 1564234073683_4958
mqtt.0	2019-07-27 15:27:19.858	info	Client [ESP32Client] publishOnSubscribe
mqtt.0	2019-07-27 15:27:19.854	info	Client [ESP32Client] subscribes on "mqtt.0.jeedom.message"
mqtt.0	2019-07-27 15:27:19.839	info	Client [ESP32Client] reconnected. Old secret 1564233751768_5596. New secret 1564234039837_8955`

However, no text is shown on the display, it remains dark ...
What am I doing wrong?

**Comment by capitaenz** [comment]
Now I understand it. No single data points, just one: message
I had thought:
message / lum
message / text
...

**Comment by prysme01** [comment]
Glad you found it.
Feel free to update the documentation or to add insights if it is not enough clear.
